package defpackage;

/* compiled from: r8-map-id-55bc5e14ca4f0ce1fb1e9e77cc19bf795986c6a69e3d49814dc3ca7768ce79b2 */
/* loaded from: /tmp/classes.dex */
public abstract class hc {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = l90.q;
        a = j2;
        b = l90.f;
        c = l90.d;
        d = l90.m;
        e = l90.H;
        long j3 = l90.s;
        f = j3;
        g = j3;
        h = l90.c;
        i = l90.g;
        j = l90.F;
        long j4 = l90.J;
        k = j4;
        l = l90.D;
        long j5 = l90.G;
        m = j5;
        n = l90.M;
        long j6 = l90.Q;
        o = j6;
        p = l90.K;
        long j7 = l90.N;
        q = j7;
        r = j3;
        s = l90.B;
        t = l90.T;
        long j8 = l90.X;
        u = j8;
        v = l90.R;
        long j9 = l90.U;
        w = j9;
        x = l90.A;
        long j10 = l90.y;
        y = j10;
        long j11 = l90.I;
        z = j11;
        A = j5;
        B = j4;
        C = j11;
        D = l90.h;
        long j12 = l90.P;
        E = j12;
        F = j7;
        G = j6;
        H = j12;
        I = j2;
        J = l90.o;
        K = l90.k;
        L = l90.l;
        M = l90.n;
        N = l90.i;
        O = l90.p;
        P = j2;
        Q = j10;
        long j13 = l90.W;
        R = j13;
        S = j9;
        T = j8;
        U = j13;
    }
}
