package defpackage;

/* compiled from: r8-map-id-55bc5e14ca4f0ce1fb1e9e77cc19bf795986c6a69e3d49814dc3ca7768ce79b2 */
/* loaded from: /tmp/classes.dex */
public abstract class ic {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = l90.x;
        a = j2;
        b = l90.e;
        c = l90.g;
        d = l90.v;
        long j3 = l90.I;
        e = j3;
        f = l90.m;
        long j4 = l90.i;
        g = j4;
        h = l90.b;
        i = l90.a;
        j = l90.E;
        long j5 = l90.D;
        k = j5;
        l = j5;
        m = l90.G;
        n = l90.L;
        long j6 = l90.K;
        o = j6;
        p = j6;
        q = l90.N;
        r = j4;
        s = l90.y;
        t = l90.S;
        long j7 = l90.R;
        u = j7;
        v = j7;
        w = l90.U;
        x = l90.z;
        y = l90.B;
        z = l90.H;
        long j8 = l90.J;
        A = j8;
        B = j8;
        C = j3;
        D = l90.h;
        E = l90.O;
        long j9 = l90.Q;
        F = j9;
        G = j9;
        H = l90.P;
        I = j2;
        J = j2;
        K = l90.u;
        L = l90.t;
        M = l90.s;
        N = l90.w;
        O = l90.j;
        P = l90.r;
        Q = l90.C;
        R = l90.V;
        long j10 = l90.X;
        S = j10;
        T = j10;
        U = l90.W;
    }
}
