package defpackage;

/* compiled from: r8-map-id-55bc5e14ca4f0ce1fb1e9e77cc19bf795986c6a69e3d49814dc3ca7768ce79b2 */
/* loaded from: /tmp/classes.dex */
public abstract class mr0 {
    public static final long A;
    public static final long A0;
    public static final qr A1;
    public static final long B;
    public static final xp B0;
    public static final long B1;
    public static final long C;
    public static final qr C0;
    public static final long C1;
    public static final xp D;
    public static final long D0;
    public static final long D1;
    public static final qr E;
    public static final long E0;
    public static final xp E1;
    public static final long F;
    public static final long F0;
    public static final qr F1;
    public static final long G;
    public static final xp G0;
    public static final long G1;
    public static final long H;
    public static final qr H0;
    public static final long H1;
    public static final xp I;
    public static final long I0;
    public static final long I1;
    public static final qr J;
    public static final long J0;
    public static final xp J1;
    public static final long K;
    public static final long K0;
    public static final qr K1;
    public static final long L;
    public static final xp L0;
    public static final long L1;
    public static final long M;
    public static final qr M0;
    public static final long M1;
    public static final xp N;
    public static final long N0;
    public static final long N1;
    public static final qr O;
    public static final long O0;
    public static final xp O1;
    public static final long P;
    public static final long P0;
    public static final qr P1;
    public static final long Q;
    public static final xp Q0;
    public static final long Q1;
    public static final long R;
    public static final qr R0;
    public static final long R1;
    public static final xp S;
    public static final long S0;
    public static final long S1;
    public static final qr T;
    public static final long T0;
    public static final xp T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final xp V0;
    public static final long W;
    public static final qr W0;
    public static final xp X;
    public static final long X0;
    public static final qr Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final qr a;
    public static final long a0;
    public static final xp a1;
    public static final long b;
    public static final long b0;
    public static final qr b1;
    public static final long c;
    public static final xp c0;
    public static final long c1;
    public static final long d;
    public static final qr d0;
    public static final long d1;
    public static final xp e;
    public static final long e0;
    public static final long e1;
    public static final qr f;
    public static final long f0;
    public static final xp f1;
    public static final long g;
    public static final long g0;
    public static final qr g1;
    public static final long h;
    public static final xp h0;
    public static final long h1;
    public static final long i;
    public static final qr i0;
    public static final long i1;
    public static final xp j;
    public static final long j0;
    public static final long j1;
    public static final qr k;
    public static final long k0;
    public static final xp k1;
    public static final long l;
    public static final long l0;
    public static final qr l1;
    public static final long m;
    public static final xp m0;
    public static final long m1;
    public static final long n;
    public static final qr n0;
    public static final long n1;
    public static final xp o;
    public static final long o0;
    public static final long o1;
    public static final qr p;
    public static final long p0;
    public static final xp p1;
    public static final long q;
    public static final long q0;
    public static final qr q1;
    public static final long r;
    public static final xp r0;
    public static final long r1;
    public static final long s;
    public static final qr s0;
    public static final long s1;
    public static final xp t;
    public static final long t0;
    public static final long t1;
    public static final qr u;
    public static final long u0;
    public static final xp u1;
    public static final long v;
    public static final long v0;
    public static final qr v1;
    public static final long w;
    public static final xp w0;
    public static final long w1;
    public static final long x;
    public static final qr x0;
    public static final long x1;
    public static final xp y;
    public static final long y0;
    public static final long y1;
    public static final qr z;
    public static final long z0;
    public static final xp z1;

    static {
        xp xpVar = vr0.a;
        qr qrVar = no0.b;
        a = qrVar;
        b = u10.r(24.0d);
        c = u10.s(16);
        d = u10.r(0.5d);
        xp xpVar2 = vr0.c;
        e = xpVar2;
        f = qrVar;
        g = u10.r(20.0d);
        h = u10.s(14);
        i = u10.r(0.2d);
        j = xpVar2;
        k = qrVar;
        l = u10.r(16.0d);
        m = u10.s(12);
        n = u10.r(0.4d);
        o = xpVar2;
        p = qrVar;
        q = u10.r(64.0d);
        r = u10.s(57);
        long r2 = u10.r(0.2d);
        cq0[] cq0VarArr = bq0.b;
        long j2 = r2 & 1095216660480L;
        if (j2 == 0) {
            ev.a("Cannot perform operation for Unspecified type.");
        }
        s = u10.B(j2, -bq0.c(r2));
        t = xpVar2;
        u = qrVar;
        v = u10.r(52.0d);
        w = u10.s(45);
        x = u10.r(0.0d);
        y = xpVar2;
        z = qrVar;
        A = u10.r(44.0d);
        B = u10.s(36);
        C = u10.r(0.0d);
        D = xpVar2;
        E = qrVar;
        F = u10.r(40.0d);
        G = u10.s(32);
        H = u10.r(0.0d);
        I = xpVar2;
        J = qrVar;
        K = u10.r(36.0d);
        L = u10.s(28);
        M = u10.r(0.0d);
        N = xpVar2;
        O = qrVar;
        P = u10.r(32.0d);
        Q = u10.s(24);
        R = u10.r(0.0d);
        S = xpVar2;
        T = qrVar;
        U = u10.r(20.0d);
        V = u10.s(14);
        W = u10.r(0.1d);
        xp xpVar3 = vr0.b;
        X = xpVar3;
        Y = qrVar;
        Z = u10.r(16.0d);
        a0 = u10.s(12);
        b0 = u10.r(0.5d);
        c0 = xpVar3;
        d0 = qrVar;
        e0 = u10.r(16.0d);
        f0 = u10.s(11);
        g0 = u10.r(0.5d);
        h0 = xpVar3;
        i0 = qrVar;
        j0 = u10.r(28.0d);
        k0 = u10.s(22);
        l0 = u10.r(0.0d);
        m0 = xpVar2;
        n0 = qrVar;
        o0 = u10.r(24.0d);
        p0 = u10.s(16);
        q0 = u10.r(0.2d);
        r0 = xpVar3;
        s0 = qrVar;
        t0 = u10.r(20.0d);
        u0 = u10.s(14);
        v0 = u10.r(0.1d);
        w0 = xpVar3;
        x0 = qrVar;
        y0 = u10.r(24.0d);
        z0 = u10.s(16);
        A0 = u10.r(0.15d);
        B0 = xpVar3;
        C0 = qrVar;
        D0 = u10.r(20.0d);
        E0 = u10.s(14);
        F0 = u10.r(0.25d);
        G0 = xpVar3;
        H0 = qrVar;
        I0 = u10.r(16.0d);
        J0 = u10.s(12);
        K0 = u10.r(0.4d);
        L0 = xpVar3;
        M0 = qrVar;
        N0 = u10.r(64.0d);
        O0 = u10.s(57);
        P0 = u10.s(0);
        Q0 = xpVar3;
        R0 = qrVar;
        S0 = u10.r(52.0d);
        T0 = u10.s(45);
        U0 = u10.s(0);
        V0 = xpVar3;
        W0 = qrVar;
        X0 = u10.r(44.0d);
        Y0 = u10.s(36);
        Z0 = u10.s(0);
        a1 = xpVar3;
        b1 = qrVar;
        c1 = u10.r(40.0d);
        d1 = u10.s(32);
        e1 = u10.s(0);
        f1 = xpVar3;
        g1 = qrVar;
        h1 = u10.r(36.0d);
        i1 = u10.s(28);
        j1 = u10.s(0);
        k1 = xpVar3;
        l1 = qrVar;
        m1 = u10.r(32.0d);
        n1 = u10.s(24);
        o1 = u10.s(0);
        p1 = xpVar3;
        q1 = qrVar;
        r1 = u10.r(20.0d);
        s1 = u10.s(14);
        t1 = u10.r(0.1d);
        xp xpVar4 = vr0.a;
        u1 = xpVar4;
        v1 = qrVar;
        w1 = u10.r(16.0d);
        x1 = u10.s(12);
        y1 = u10.r(0.5d);
        z1 = xpVar4;
        A1 = qrVar;
        B1 = u10.r(16.0d);
        C1 = u10.s(11);
        D1 = u10.r(0.5d);
        E1 = xpVar4;
        F1 = qrVar;
        G1 = u10.r(28.0d);
        H1 = u10.s(22);
        I1 = u10.s(0);
        J1 = xpVar3;
        K1 = qrVar;
        L1 = u10.r(24.0d);
        M1 = u10.s(16);
        N1 = u10.r(0.15d);
        O1 = xpVar4;
        P1 = qrVar;
        Q1 = u10.r(20.0d);
        R1 = u10.s(14);
        S1 = u10.r(0.1d);
        T1 = xpVar4;
    }
}
